# ------------------------------------------------------------------------------
# OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
# ------------------------------------------------------------------------------
# Name.......: outputs.tf
# Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
# Editor.....: Stefan Oehrli
# Date.......: 2026-05-14
# Version....: v0.1.0
# Purpose....: Module outputs for iam_mfa_oma - all values needed for DB-side MFA config
# Notes......: Sensitive outputs (oauth_client_secret, smtp_password,
#              db_mfa_config_commands) require: terraform output -json
# Reference..: https://github.com/oehrlis/oci-labs
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ------------------------------------------------------------------------------

output "iam_domain_url" {
  description = "Identity Domain URL, used as MFA_OMA_IAM_DOMAIN_URL in Oracle DB config."
  value       = data.oci_identity_domain.domain.url
}

output "oauth_client_id" {
  description = "OAuth Confidential Application client ID (app name in Identity Domain)."
  value       = oci_identity_domains_application.oauth_app.name
}

output "oauth_client_secret" {
  description = "OAuth Confidential Application client secret. Available once after apply; retrieve via OCI Console if lost."
  sensitive   = true
  value       = oci_identity_domains_application.oauth_app.client_secret
}

output "smtp_host" {
  description = "OCI Email Delivery SMTP host for the configured region."
  value       = local.smtp_host
}

output "smtp_port" {
  description = "OCI Email Delivery SMTP port (STARTTLS)."
  value       = 587
}

output "smtp_sender_email" {
  description = "Approved Sender email address."
  value       = var.smtp_sender_email
}

output "smtp_username" {
  description = "SMTP credential username generated by OCI (OCID-based format)."
  value       = oci_identity_smtp_credential.smtp_cred.username
}

output "smtp_password" {
  description = "SMTP credential password. Shown only once - save immediately after apply."
  sensitive   = true
  value       = oci_identity_smtp_credential.smtp_cred.password
}

output "smtp_user_ocid" {
  description = "OCID of the dedicated SMTP IAM user."
  value       = oci_identity_user.smtp_user.id
}

output "approved_sender_ocid" {
  description = "OCID of the OCI Email Delivery Approved Sender."
  value       = oci_email_sender.approved_sender.id
}

output "db_mfa_config_commands" {
  description = "ALTER SYSTEM commands for Oracle DB-side MFA setup (copy-paste ready)."
  sensitive   = true
  value       = <<-EOT
    -- Run as SYSDBA on the Oracle Database:
    ALTER SYSTEM SET MFA_OMA_IAM_DOMAIN_URL = '${data.oci_identity_domain.domain.url}' SCOPE=BOTH;
    ALTER SYSTEM SET MFA_SMTP_HOST          = '${local.smtp_host}' SCOPE=BOTH;
    ALTER SYSTEM SET MFA_SMTP_PORT          = 587 SCOPE=BOTH;
    ALTER SYSTEM SET MFA_SENDER_EMAIL_ID    = '${var.smtp_sender_email}' SCOPE=BOTH;
  EOT
}

# ------------------------------------------------------------------------------
# EOF
# ------------------------------------------------------------------------------
